SOURCE_DIR = Sys.getenv("SOURCE_DIR")
LOG_DIR = Sys.getenv("LOG_DIR")
DATA_DIR = Sys.getenv("DATA_DIR")
ARTIFACTS_DIR = Sys.getenv("ARTIFACTS_DIR")
RESULTS_DIR = Sys.getenv("RESULTS_DIR")

print(SOURCE_DIR)
print(LOG_DIR)
print(DATA_DIR)
print(ARTIFACTS_DIR)
print(RESULTS_DIR)
